version: '3.8'  
  
services:  
  mongodb:  
    image: mongo:latest  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/data/db  
  
  web:  
    build: .  
    ports:  
      - "8000:8000"  
    depends_on:  
      - mongodb  
    environment:  
      - MONGODB_HOST=mongodb  
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=True  
      - SECRET_KEY=${SECRET_KEY} #Générer automatiquement lors de la création du projet dans settings.py
    volumes:  
      - .:/app  

  test:  
      build: .  
      volumes:  
        - .:/app  
      depends_on:  
        - web  
        - mongodb  
      environment:  
        - DJANGO_SETTINGS_MODULE=backend_with_mongodb.settings  
      command: >  
        sh -c "  
          playwright install &&  
          python -m pytest tests/test_metadata_workflow.py -v  
        "  
      networks:  
        - default
  
volumes:  
  mongodb_data: