version: '3.8'  
  
services:  
  mongodb:  
    image: mongo:latest  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/data/db  
  
  web:  
    build: .  
    ports:  
      - "8000:8000"  
    depends_on:  
      - mongodb  
    environment:  
      - MONGODB_HOST=mongodb  
      - DEEPSEEK_API_KEY=sk-8793ca669da3492db76a7111ac6d71c5
      - DEBUG=True  
      - SECRET_KEY="django-insecure-^b9h-e^uo!*k9rs=jf7ar$7@*x#9sf8pn=mi9f4_*z%h9^h%($"  

    volumes:  
      - .:/app  
  
volumes:  
  mongodb_data: