version: '3.8'  
  
services:  
  mongodb:  
    image: mongo:latest  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/data/db  
    networks:  
      - hdp-network  
  
  web:  
    build: .  
    ports:  
      - "8001:8000"  
    depends_on:  
      - mongodb  
    environment:  
      - MONGODB_HOST=mongodb  
      - ATLAS_URL=http://172.26.0.2:21000  # Nouvelle IP dans hdp-network  
      - ATLAS_USERNAME=admin  
      - ATLAS_PASSWORD=ensias123  
    volumes:  
      - .:/app  
    networks:  
      - hdp-network  
  
volumes:  
  mongodb_data:  
  
networks:  
  hdp-network:  
    external: true